apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentserv-deployment
  labels:
    app: commentserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: commentserv
  template:
    metadata:
      labels:
        app: commentserv
    spec:        
      containers:
      - name: commentserv
        image: commentserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
        env:
        - name: PORT
          value: "8090"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: commentserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: commentserv-service
spec:
  selector:
    app: commentserv
  ports:
    - name: commentserv-service
      port: 8090
      targetPort: 8090
      protocol: TCP