apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:        
      containers:
      - name: gateway
        image: gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: USERSERV_URL
          value: "http://userserv-service.default.svc.cluster.local:8088/api/v1"
        - name: VIDEOSERV_URL
          value: "http://videoserv-service.default.svc.cluster.local:8089/api/v1"
        - name: COMMENTSERV_URL
          value: "http://commentserv-service.default.svc.cluster.local:8090/api/v1"
        - name: SUBSCRIPTIONSERV_URL
          value: "http://subscriptionserv-service.default.svc.cluster.local:8091/api/v1" 
        - name: PLAYLISTSERV_URL
          value: "http://playlistserv-service.default.svc.cluster.local:8092/api/v1"           
        - name: LIKESERV_URL
          value: "http://likeserv-service.default.svc.cluster.local:8093/api/v1"           
        - name: HISTORYSERV_URL
          value: "http://historyserv-service.default.svc.cluster.local:8094/api/v1"           
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: gateway-service
      port: 8081
      targetPort: 8081  
      protocol: TCP