apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyserv-deployment
  namespace: project1
  labels:
    app: historyserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: historyserv
  template:
    metadata:
      labels:
        app: historyserv
    spec:
      containers:
      - name: historyserv
        image: historyserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8094
        env:
        - name: PORT
          value: "8094"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: historyserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: historyserv-service
  namespace: project1
spec:
  selector:
    app: historyserv
  ports:
    - name: historyserv-service
      port: 8094
      targetPort: 8094
      protocol: TCP