apiVersion: apps/v1
kind: Deployment
metadata:
  name: likeserv-deployment
  namespace: project1
  labels:
    app: likeserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: likeserv
  template:
    metadata:
      labels:
        app: likeserv
    spec:
      containers:
      - name: likeserv
        image: likeserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8093
        env:
        - name: PORT
          value: "8093"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: likeserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: likeserv-service
  namespace: project1
spec:
  selector:
    app: likeserv
  ports:
    - name: likeserv-service
      port: 8093
      targetPort: 8093
      protocol: TCP