apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationserv-deployment
  namespace: project1
  labels:
    app: notificationserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: notificationserv
  template:
    metadata:
      labels:
        app: notificationserv
    spec:
      containers:
      - name: notificationserv
        image: notificationserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8095
        env:
        - name: PORT
          value: "8095"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: notificationserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: notificationserv-service
  namespace: project1
spec:
  selector:
    app: notificationserv
  ports:
    - name: notificationserv-service
      port: 8095
      targetPort: 8095
      protocol: TCP