apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlistserv-deployment
  labels:
    app: playlistserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: playlistserv
  template:
    metadata:
      labels:
        app: playlistserv
    spec:        
      containers:
      - name: playlistserv
        image: playlistserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8092
        env:
        - name: PORT
          value: "8092"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: playlistserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: playlistserv-service
spec:
  selector:
    app: playlistserv
  ports:
    - name: playlistserv-service
      port: 8092
      targetPort: 8092
      protocol: TCP