apiVersion: apps/v1
kind: Deployment
metadata:
  name: prj1-playlistserv-deployment
  labels:
    app: prj1-playlistserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prj1-playlistserv
  template:
    metadata:
      labels:
        app: prj1-playlistserv
    spec:        
      containers:
      - name: prj1-playlistserv
        image: prj1-playlistserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8092
        env:
        - name: PORT
          value: "8092"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: prj1-database-secret
              key: playlistserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: prj1-playlistserv-service
spec:
  selector:
    app: prj1-playlistserv
  ports:
    - name: prj1-playlistserv-service
      port: 8092
      targetPort: 8092
      protocol: TCP