apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionserv-deployment
  namespace: project1
  labels:
    app: subscriptionserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: subscriptionserv
  template:
    metadata:
      labels:
        app: subscriptionserv
    spec:
      containers:
      - name: subscriptionserv
        image: subscriptionserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8091
        env:
        - name: PORT
          value: "8091"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: subscriptionserv-mongodb-url             
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptionserv-service
  namespace: project1
spec:
  selector:
    app: subscriptionserv
  ports:
    - name: subscriptionserv-service
      port: 8091
      targetPort: 8091
      protocol: TCP