apiVersion: apps/v1
kind: Deployment
metadata:
  name: userserv-deployment
  labels:
    app: userserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: userserv
  template:
    metadata:
      labels:
        app: userserv
    spec:        
      containers:
      - name: userserv
        image: userserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8088
        env:
        - name: PORT
          value: "8088"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: userserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: userserv-service
spec:
  selector:
    app: userserv
  ports:
    - name: userserv-service
      port: 8088
      targetPort: 8088
      protocol: TCP