apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoserv-deployment
  labels:
    app: videoserv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: videoserv
  template:
    metadata:
      labels:
        app: videoserv
    spec:        
      containers:
      - name: videoserv
        image: videoserv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8089
        env:
        - name: PORT
          value: "8089"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: videoserv-mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: videoserv-service
spec:
  selector:
    app: videoserv
  ports:
    - name: videoserv-service
      port: 8089
      targetPort: 8089
      protocol: TCP