apiVersion: v1
kind: Secret
metadata:
  name: prj1-userserv-secret
type: Opaque
data:
  port: ODA4OA==
  mongodb-url: bW9uZ29kYitzcnY6Ly90cm91bmc6MTIzUVdFYXNkQGNsdXN0ZXIwLm9qZnBoLm1vbmdvZGIubmV0L3VzZXJfc2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=